
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPIPEDOUBLE_QUOTES EQ PIPE SINGLE_QUOTES SYMBOLSexpr : SYMBOLS\n            | SYMBOLS args\n            | SYMBOLS EQ SYMBOLS\n            | expr PIPE exprexpr : SYMBOLS EQ SINGLE_QUOTES\n            | SYMBOLS EQ DOUBLE_QUOTES args : arg\n             | args argarg : SYMBOLSarg  : SINGLE_QUOTES\n            | DOUBLE_QUOTES'
    
_lr_action_items = {'SYMBOLS':([0,2,3,4,5,6,7,8,9,11,],[2,4,2,-9,4,12,-10,-11,-7,-8,]),'$end':([1,2,4,5,7,8,9,10,11,12,13,14,],[0,-1,-9,-2,-10,-11,-7,-4,-8,-3,-5,-6,]),'PIPE':([1,2,4,5,7,8,9,10,11,12,13,14,],[3,-1,-9,-2,-10,-11,-7,-4,-8,-3,-5,-6,]),'EQ':([2,],[6,]),'SINGLE_QUOTES':([2,4,5,6,7,8,9,11,],[7,-9,7,13,-10,-11,-7,-8,]),'DOUBLE_QUOTES':([2,4,5,6,7,8,9,11,],[8,-9,8,14,-10,-11,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,],[1,10,]),'args':([2,],[5,]),'arg':([2,5,],[9,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> SYMBOLS','expr',1,'p_expr_commands','yacc.py',28),
  ('expr -> SYMBOLS args','expr',2,'p_expr_commands','yacc.py',29),
  ('expr -> SYMBOLS EQ SYMBOLS','expr',3,'p_expr_commands','yacc.py',30),
  ('expr -> expr PIPE expr','expr',3,'p_expr_commands','yacc.py',31),
  ('expr -> SYMBOLS EQ SINGLE_QUOTES','expr',3,'p_expr_eq_quotes','yacc.py',48),
  ('expr -> SYMBOLS EQ DOUBLE_QUOTES','expr',3,'p_expr_eq_quotes','yacc.py',49),
  ('args -> arg','args',1,'p_args','yacc.py',54),
  ('args -> args arg','args',2,'p_args','yacc.py',55),
  ('arg -> SYMBOLS','arg',1,'p_arg','yacc.py',65),
  ('arg -> SINGLE_QUOTES','arg',1,'p_arg_quotes','yacc.py',70),
  ('arg -> DOUBLE_QUOTES','arg',1,'p_arg_quotes','yacc.py',71),
]
